In [1]:
import pandas as pd

In [2]:
domestic_data=pd.read_csv("cleaned_resources/new_dom_clean_data.csv")
#we imported the csv

In [3]:
domestic_data.head()
#we can inspect the dataframe here

        month        country price_type   market commodity  price
0  2020-05-01  Cote d'Ivoire     Retail  Abidjan   Attieke   0.61
1  2020-04-01  Cote d'Ivoire     Retail  Abidjan   Attieke   0.59
2  2020-03-01  Cote d'Ivoire     Retail  Abidjan   Attieke   0.61
3  2020-02-01  Cote d'Ivoire     Retail  Abidjan   Attieke   0.63
4  2020-01-01  Cote d'Ivoire     Retail  Abidjan   Attieke   0.68

In [4]:
domestic_data["month"]= pd.to_datetime(domestic_data['month'])
#before we manipulate any dates we need to make sure they are datetime, we did this previously but it never hurts to double check

In [5]:
domestic_data['Year'] = domestic_data['month'].dt.year
# for a variety of the charts we want to make, we want to make them show data based on the year hence we need to create a new
#column

In [6]:
domestic_data

            month        country price_type    market commodity  price  Year
0      2020-05-01  Cote d'Ivoire     Retail   Abidjan   Attieke   0.61  2020
1      2020-04-01  Cote d'Ivoire     Retail   Abidjan   Attieke   0.59  2020
2      2020-03-01  Cote d'Ivoire     Retail   Abidjan   Attieke   0.61  2020
3      2020-02-01  Cote d'Ivoire     Retail   Abidjan   Attieke   0.63  2020
4      2020-01-01  Cote d'Ivoire     Retail   Abidjan   Attieke   0.68  2020
...           ...            ...        ...       ...       ...    ...   ...
130738 2010-05-01          Ghana  Wholesale  Techiman       Yam   0.51  2010
130739 2010-04-01          Ghana  Wholesale  Techiman       Yam   0.37  2010
130740 2010-03-01          Ghana  Wholesale  Techiman       Yam   0.36  2010
130741 2010-02-01          Ghana  Wholesale  Techiman       Yam   0.36  2010
130742 2010-01-01          Ghana  Wholesale  Techiman       Yam   0.33  2010

[130743 rows x 7 columns]

In [7]:
national_average_data=domestic_data[domestic_data['market']=='National Average']
national_average_data=national_average_data.sort_values('month', ascending=False)

wholesale_average_data=national_average_data[national_average_data['price_type']=='Wholesale']
wholesale_average_data
#instead of averaging all of the data, we can look at the national average. Additionally we noticed that retail has 
#strange discrepencies so we made the data more narrow and focused on Wholesale

,month,country,price_type,market,commodity,price,Year
114984,2020-06-01,Chile,Wholesale,National Average,Wheat,0.24,2020
128824,2020-06-01,Ukraine,Wholesale,National Average,Wheat (flour),0.31,2020
81855,2020-06-01,China,Wholesale,National Average,Rice,0.56,2020
80298,2020-06-01,Uruguay,Wholesale,National Average,Rice,0.19,2020
128700,2020-06-01,Uzbekistan,Wholesale,National Average,Wheat (flour),0.38,2020
...,...,...,...,...,...,...,...
34513,2010-01-01,Honduras,Wholesale,National Average,Maize (white),0.31,2010
34015,2010-01-01,Guatemala,Wholesale,National Average,Maize (white),0.33,2010
33520,2010-01-01,Costa Rica,Wholesale,National Average,Maize (white),0.50,2010
33039,2010-01-01,Russian Federation,Wholesale,National Average,Maize,0.17,2010
29336,2010-01-01,Israel,Wholesale,National Average,Maize,0.26,2010

In [8]:
retail_average_data=national_average_data[national_average_data['price_type']=='Retail']
retail_average_data

#just to demonstrate this, note that Russia has two prices for wheat in the same month that vary wildly.

,month,country,price_type,market,commodity,price,Year
126826,2020-06-01,Russian Federation,Retail,National Average,Wheat (flour),39.26,2020
126588,2020-06-01,Russian Federation,Retail,National Average,Wheat (flour),0.57,2020
69060,2020-06-01,Kyrgyzstan,Retail,National Average,Potatoes,0.49,2020
79369,2020-06-01,Russian Federation,Retail,National Average,Rice,1.15,2020
84439,2020-06-01,Colombia,Retail,National Average,Rice,1.03,2020
...,...,...,...,...,...,...,...
126825,2010-01-01,South Africa,Retail,National Average,Wheat (flour),0.92,2010
23664,2010-01-01,Tunisia,Retail,National Average,Chicken meat,2.98,2010
23433,2010-01-01,Georgia,Retail,National Average,Chicken meat,3.81,2010
21577,2010-01-01,Israel,Retail,National Average,Chicken meat,5.78,2010
129931,2010-01-01,Zambia,Retail,National Average,White roller maize meal,0.44,2010

In [9]:
wholesale_average_data_group=wholesale_average_data.groupby(['Year','country','commodity'])

#we want to break the data down by year, country and commodity. Then we want to get the average price per year for each
#commodity in the country. We created the below dataframe from this group by object to acheive this

In [10]:
line_graph_annual_data =wholesale_average_data_group=wholesale_average_data_group[['price']].mean()
line_graph_annual_data

                                   price
Year country    commodity
2010 Chile      Maize (yellow)  0.222500
                Wheat           0.217500
     Costa Rica Beans (black)   1.693333
                Beans (red)     1.897500
                Maize (white)   0.534167
...                                  ...
2020 Ukraine    Wheat           0.218333
                Wheat (flour)   0.315000
     Uruguay    Rice            0.186667
                Wheat           0.200000
     Uzbekistan Wheat (flour)   0.281667

[318 rows x 1 columns]

In [11]:
line_graph_annual_data.head(40)
#we just want to confirm that multiple years are being captured

                                                 price
Year country            commodity
2010 Chile              Maize (yellow)        0.222500
                        Wheat                 0.217500
     Costa Rica         Beans (black)         1.693333
                        Beans (red)           1.897500
                        Maize (white)         0.534167
     Guatemala          Beans (black)         1.001667
                        Maize (white)         0.327500
     Honduras           Beans (red)           1.119167
                        Maize (white)         0.286667
     Israel             Maize                 0.274167
                        Wheat                 0.282500
     Italy              Rice                  0.586667
                        Wheat                 0.242500
                        Wheat (milling soft)  0.240000
     Kazakhstan         Beef meat             5.119091
                        Potatoes              0.460000
                        Wheat (flour)         0.366364
     Philippines        Maize (white)         0.333333
                        Maize (yellow)        0.319167
                        Rice                  0.630000
     Russian Federation Maize                 0.210000
                        Wheat                 0.174167
     Ukraine            Wheat                 0.166667
                        Wheat (flour)         0.258333
     Uruguay            Rice                  0.243000
                        Wheat                 0.224000
     Uzbekistan         Wheat (flour)         0.287500
2011 Chile              Maize (yellow)        0.293333
                        Wheat                 0.304167
     Costa Rica         Beans (black)         1.660833
                        Beans (red)           2.421667
                        Maize (white)         0.723333
     Guatemala          Beans (black)         1.034167
                        Maize (white)         0.475000
     Honduras           Beans (red)           1.530000
                        Maize (white)         0.445833
     Israel             Maize                 0.370833
                        Wheat                 0.385833
     Italy              Rice                  0.782222
                        Wheat                 0.400833

In [12]:
domestic_data_grouped = domestic_data.groupby(['Year','country', 'commodity'])

In [13]:
year_commodity_dataframe=domestic_data_grouped[["price"]].mean()

In [14]:
year_commodity_dataframe.head(25)

                                                 price
Year country     commodity
2010 Afghanistan Bread                        0.695000
                 Wheat                        0.317292
                 Wheat (flour)                0.428125
     Angola      Cassava (flour)              2.340833
                 Maize (flour)                2.635000
                 Milk (powder)              111.935000
                 Rice                         2.547500
                 Sugar                        2.450833
     Argentina   Maize (yellow)               0.135833
                 Wheat                        0.157500
     Armenia     Bread (first grade flour)    0.916667
                 Bread (high grade flour)     1.045000
                 Potatoes                     0.490833
                 Wheat (flour)                0.533333
     Azerbaijan  Beef meat                    7.160000
                 Bread (high grade flour)     0.683333
                 Milk                         1.170000
                 Mutton meat                  8.178333
                 Potatoes                     0.801667
                 Wheat (flour)                0.776667
     Bangladesh  Rice                         0.486667
                 Wheat (flour)                0.335000
     Belarus     Bread (high grade flour)     1.067500
                 Potatoes                     0.517500
                 Wheat (flour)                0.652917

In [15]:
domestic_data_sorted = domestic_data.sort_values('month', ascending=False)
domestic_data_sorted

,month,country,price_type,market,commodity,price,Year
78640,2020-06-01,Namibia,Retail,Mariental,Rice,1.32,2020
126588,2020-06-01,Russian Federation,Retail,National Average,Wheat (flour),0.57,2020
114828,2020-06-01,Brazil,Wholesale,ParanÃ¡,Wheat,0.23,2020
104232,2020-06-01,Sudan,Wholesale,El Obeid,Sorghum,0.92,2020
83143,2020-06-01,Pakistan,Retail,Karachi,Rice,0.57,2020
...,...,...,...,...,...,...,...
31051,2010-01-01,Niger,Retail,Agadez,Maize,0.53,2010
31287,2010-01-01,Panama,Retail,Panama City,Maize,0.54,2010
117472,2010-01-01,Sudan,Wholesale,Khartoum,Wheat,0.57,2010
31412,2010-01-01,Panama,Wholesale,Panama City,Maize,0.37,2010
130742,2010-01-01,Ghana,Wholesale,Techiman,Yam,0.33,2010

In [16]:
first_day_data = wholesale_average_data[wholesale_average_data['month']=='2010-01-01']
first_day_data

#i want to remove all all rows from last day data, that aren't also in first day data.
#this is for a dataframe that will be used to make a bar chart that compares the price differences for a commodity
#in the years of 2010 and 2020

,month,country,price_type,market,commodity,price,Year
2287,2010-01-01,Costa Rica,Wholesale,National Average,Beans (black),1.64,2010
115109,2010-01-01,Chile,Wholesale,National Average,Wheat,0.23,2010
129071,2010-01-01,Italy,Wholesale,National Average,Wheat (milling soft),0.21,2010
69939,2010-01-01,Kazakhstan,Wholesale,National Average,Potatoes,0.44,2010
2908,2010-01-01,Guatemala,Wholesale,National Average,Beans (black),1.01,2010
118410,2010-01-01,Italy,Wholesale,National Average,Wheat,0.24,2010
116312,2010-01-01,Israel,Wholesale,National Average,Wheat,0.25,2010
117850,2010-01-01,Ukraine,Wholesale,National Average,Wheat,0.15,2010
97419,2010-01-01,Philippines,Wholesale,National Average,Rice,0.62,2010
97169,2010-01-01,Italy,Wholesale,National Average,Rice,0.54,2010
118040,2010-01-01,Russian Federation,Wholesale,National Average,Wheat,0.15,2010
128823,2010-01-01,Uzbekistan,Wholesale,National Average,Wheat (flour),0.29,2010
8997,2010-01-01,Kazakhstan,Wholesale,National Average,Beef meat,4.90,2010
128949,2010-01-01,Ukraine,Wholesale,National Average,Wheat (flour),0.22,2010
6594,2010-01-01,Honduras,Wholesale,National Average,Beans (red),0.72,2010
5353,2010-01-01,Costa Rica,Wholesale,National Average,Beans (red),1.87,2010
122813,2010-01-01,Kazakhstan,Wholesale,National Average,Wheat (flour),0.35,2010
43336,2010-01-01,Philippines,Wholesale,National Average,Maize (yellow),0.29,2010
42624,2010-01-01,Chile,Wholesale,National Average,Maize (yellow),0.22,2010
37016,2010-01-01,Philippines,Wholesale,National Average,Maize (white),0.37,2010
34513,2010-01-01,Honduras,Wholesale,National Average,Maize (white),0.31,2010
34015,2010-01-01,Guatemala,Wholesale,National Average,Maize (white),0.33,2010
33520,2010-01-01,Costa Rica,Wholesale,National Average,Maize (white),0.50,2010
33039,2010-01-01,Russian Federation,Wholesale,National Average,Maize,0.17,2010
29336,2010-01-01,Israel,Wholesale,National Average,Maize,0.26,2010

In [17]:
last_day_data = wholesale_average_data[wholesale_average_data['month']=='2020-01-01']
last_day_data

#we need to get the data for the last day as well

,month,country,price_type,market,commodity,price,Year
122694,2020-01-01,Kazakhstan,Wholesale,National Average,Wheat (flour),0.40,2020
117478,2020-01-01,Uruguay,Wholesale,National Average,Wheat,0.19,2020
2792,2020-01-01,Guatemala,Wholesale,National Average,Beans (black),0.99,2020
128954,2020-01-01,Italy,Wholesale,National Average,Wheat (milling soft),0.22,2020
32919,2020-01-01,Russian Federation,Wholesale,National Average,Maize,0.16,2020
81860,2020-01-01,China,Wholesale,National Average,Rice,0.58,2020
118293,2020-01-01,Italy,Wholesale,National Average,Wheat,0.30,2020
69820,2020-01-01,Kazakhstan,Wholesale,National Average,Potatoes,0.26,2020
128377,2020-01-01,China,Wholesale,National Average,Wheat (flour),0.52,2020
42505,2020-01-01,Chile,Wholesale,National Average,Maize (yellow),0.19,2020
97299,2020-01-01,Philippines,Wholesale,National Average,Rice,0.65,2020
43216,2020-01-01,Philippines,Wholesale,National Average,Maize (yellow),0.43,2020
128829,2020-01-01,Ukraine,Wholesale,National Average,Wheat (flour),0.32,2020
116192,2020-01-01,Israel,Wholesale,National Average,Wheat,0.30,2020
2167,2020-01-01,Costa Rica,Wholesale,National Average,Beans (black),1.76,2020
97070,2020-01-01,Italy,Wholesale,National Average,Rice,0.39,2020
80303,2020-01-01,Uruguay,Wholesale,National Average,Rice,0.19,2020
114989,2020-01-01,Chile,Wholesale,National Average,Wheat,0.23,2020
36896,2020-01-01,Philippines,Wholesale,National Average,Maize (white),0.33,2020
5233,2020-01-01,Costa Rica,Wholesale,National Average,Beans (red),2.09,2020
33897,2020-01-01,Guatemala,Wholesale,National Average,Maize (white),0.37,2020
34394,2020-01-01,Honduras,Wholesale,National Average,Maize (white),0.39,2020
117730,2020-01-01,Ukraine,Wholesale,National Average,Wheat,0.22,2020
8878,2020-01-01,Kazakhstan,Wholesale,National Average,Beef meat,5.56,2020
117920,2020-01-01,Russian Federation,Wholesale,National Average,Wheat,0.20,2020
128705,2020-01-01,Uzbekistan,Wholesale,National Average,Wheat (flour),0.24,2020
6474,2020-01-01,Honduras,Wholesale,National Average,Beans (red),0.88,2020
115115,2020-01-01,China,Wholesale,National Average,Wheat,0.35,2020
29216,2020-01-01,Israel,Wholesale,National Average,Maize,0.26,2020

In [18]:
#we need to make sure the values in the first and last day match up. There's a slight discrepency in the shape between these
#two dataframes so we ran this code to fix that

# Get the values in a common column (country) from df1
common_ids = first_day_data['country'].values

# Filter rows in df2 based on the common column values
filtered_last_day = last_day_data[last_day_data['country'].isin(common_ids)]

filtered_last_day=filtered_last_day.sort_values('country', ascending=False)
filtered_last_day

,month,country,price_type,market,commodity,price,Year
128705,2020-01-01,Uzbekistan,Wholesale,National Average,Wheat (flour),0.24,2020
128829,2020-01-01,Ukraine,Wholesale,National Average,Wheat (flour),0.32,2020
117730,2020-01-01,Ukraine,Wholesale,National Average,Wheat,0.22,2020
32919,2020-01-01,Russian Federation,Wholesale,National Average,Maize,0.16,2020
117920,2020-01-01,Russian Federation,Wholesale,National Average,Wheat,0.20,2020
36896,2020-01-01,Philippines,Wholesale,National Average,Maize (white),0.33,2020
97299,2020-01-01,Philippines,Wholesale,National Average,Rice,0.65,2020
43216,2020-01-01,Philippines,Wholesale,National Average,Maize (yellow),0.43,2020
122694,2020-01-01,Kazakhstan,Wholesale,National Average,Wheat (flour),0.40,2020
69820,2020-01-01,Kazakhstan,Wholesale,National Average,Potatoes,0.26,2020
8878,2020-01-01,Kazakhstan,Wholesale,National Average,Beef meat,5.56,2020
97070,2020-01-01,Italy,Wholesale,National Average,Rice,0.39,2020
118293,2020-01-01,Italy,Wholesale,National Average,Wheat,0.30,2020
128954,2020-01-01,Italy,Wholesale,National Average,Wheat (milling soft),0.22,2020
116192,2020-01-01,Israel,Wholesale,National Average,Wheat,0.30,2020
29216,2020-01-01,Israel,Wholesale,National Average,Maize,0.26,2020
34394,2020-01-01,Honduras,Wholesale,National Average,Maize (white),0.39,2020
6474,2020-01-01,Honduras,Wholesale,National Average,Beans (red),0.88,2020
2792,2020-01-01,Guatemala,Wholesale,National Average,Beans (black),0.99,2020
33897,2020-01-01,Guatemala,Wholesale,National Average,Maize (white),0.37,2020
2167,2020-01-01,Costa Rica,Wholesale,National Average,Beans (black),1.76,2020
5233,2020-01-01,Costa Rica,Wholesale,National Average,Beans (red),2.09,2020
114989,2020-01-01,Chile,Wholesale,National Average,Wheat,0.23,2020
42505,2020-01-01,Chile,Wholesale,National Average,Maize (yellow),0.19,2020

In [19]:
filtered_last_day_index=filtered_last_day.reset_index()
filtered_last_day_index=filtered_last_day_index[['month','country',"price_type",'market','commodity','price','Year']]
filtered_last_day_index

#we also need to align the indexes so the empty dataframe, first and last day dataframes are aligned

,month,country,price_type,market,commodity,price,Year
0,2020-01-01,Uzbekistan,Wholesale,National Average,Wheat (flour),0.24,2020
1,2020-01-01,Ukraine,Wholesale,National Average,Wheat (flour),0.32,2020
2,2020-01-01,Ukraine,Wholesale,National Average,Wheat,0.22,2020
3,2020-01-01,Russian Federation,Wholesale,National Average,Maize,0.16,2020
4,2020-01-01,Russian Federation,Wholesale,National Average,Wheat,0.20,2020
5,2020-01-01,Philippines,Wholesale,National Average,Maize (white),0.33,2020
6,2020-01-01,Philippines,Wholesale,National Average,Rice,0.65,2020
7,2020-01-01,Philippines,Wholesale,National Average,Maize (yellow),0.43,2020
8,2020-01-01,Kazakhstan,Wholesale,National Average,Wheat (flour),0.40,2020
9,2020-01-01,Kazakhstan,Wholesale,National Average,Potatoes,0.26,2020
10,2020-01-01,Kazakhstan,Wholesale,National Average,Beef meat,5.56,2020
11,2020-01-01,Italy,Wholesale,National Average,Rice,0.39,2020
12,2020-01-01,Italy,Wholesale,National Average,Wheat,0.30,2020
13,2020-01-01,Italy,Wholesale,National Average,Wheat (milling soft),0.22,2020
14,2020-01-01,Israel,Wholesale,National Average,Wheat,0.30,2020
15,2020-01-01,Israel,Wholesale,National Average,Maize,0.26,2020
16,2020-01-01,Honduras,Wholesale,National Average,Maize (white),0.39,2020
17,2020-01-01,Honduras,Wholesale,National Average,Beans (red),0.88,2020
18,2020-01-01,Guatemala,Wholesale,National Average,Beans (black),0.99,2020
19,2020-01-01,Guatemala,Wholesale,National Average,Maize (white),0.37,2020
20,2020-01-01,Costa Rica,Wholesale,National Average,Beans (black),1.76,2020
21,2020-01-01,Costa Rica,Wholesale,National Average,Beans (red),2.09,2020
22,2020-01-01,Chile,Wholesale,National Average,Wheat,0.23,2020
23,2020-01-01,Chile,Wholesale,National Average,Maize (yellow),0.19,2020

In [20]:
difference_price=filtered_last_day_index[["country",'market',"commodity"]]
difference_price

#we need to create an empty dataframe to append the price differences to.

               country            market             commodity
0           Uzbekistan  National Average         Wheat (flour)
1              Ukraine  National Average         Wheat (flour)
2              Ukraine  National Average                 Wheat
3   Russian Federation  National Average                 Maize
4   Russian Federation  National Average                 Wheat
5          Philippines  National Average         Maize (white)
6          Philippines  National Average                  Rice
7          Philippines  National Average        Maize (yellow)
8           Kazakhstan  National Average         Wheat (flour)
9           Kazakhstan  National Average              Potatoes
10          Kazakhstan  National Average             Beef meat
11               Italy  National Average                  Rice
12               Italy  National Average                 Wheat
13               Italy  National Average  Wheat (milling soft)
14              Israel  National Average                 Wheat
15              Israel  National Average                 Maize
16            Honduras  National Average         Maize (white)
17            Honduras  National Average           Beans (red)
18           Guatemala  National Average         Beans (black)
19           Guatemala  National Average         Maize (white)
20          Costa Rica  National Average         Beans (black)
21          Costa Rica  National Average           Beans (red)
22               Chile  National Average                 Wheat
23               Chile  National Average        Maize (yellow)

In [21]:
# Get the values in a common column (e.g., 'country') from df1
common_ids = filtered_last_day['country'].values

# Filter rows in df2 based on the common column values
filtered_first_day = first_day_data[first_day_data['country'].isin(common_ids)]
#as we meantioned earlier, the dataframes were not the same shape so could not be properly compared. We dropped the extra dataframe 
#from the 2010 dataset
print(filtered_first_day.shape)
print(filtered_last_day.shape)

(25, 7)
(24, 7)

In [22]:
filtered_first_day_test = filtered_first_day.reset_index()
test_two=filtered_first_day_test[["month","country","price_type","market","commodity","price","Year"]]
test_two
#test_two.drop(index=row_index, inplace=True)

#we need to fix the index here as well so they match

,month,country,price_type,market,commodity,price,Year
0,2010-01-01,Costa Rica,Wholesale,National Average,Beans (black),1.64,2010
1,2010-01-01,Chile,Wholesale,National Average,Wheat,0.23,2010
2,2010-01-01,Italy,Wholesale,National Average,Wheat (milling soft),0.21,2010
3,2010-01-01,Kazakhstan,Wholesale,National Average,Potatoes,0.44,2010
4,2010-01-01,Guatemala,Wholesale,National Average,Beans (black),1.01,2010
5,2010-01-01,Italy,Wholesale,National Average,Wheat,0.24,2010
6,2010-01-01,Israel,Wholesale,National Average,Wheat,0.25,2010
7,2010-01-01,Ukraine,Wholesale,National Average,Wheat,0.15,2010
8,2010-01-01,Philippines,Wholesale,National Average,Rice,0.62,2010
9,2010-01-01,Italy,Wholesale,National Average,Rice,0.54,2010
10,2010-01-01,Russian Federation,Wholesale,National Average,Wheat,0.15,2010
11,2010-01-01,Uzbekistan,Wholesale,National Average,Wheat (flour),0.29,2010
12,2010-01-01,Kazakhstan,Wholesale,National Average,Beef meat,4.90,2010
13,2010-01-01,Ukraine,Wholesale,National Average,Wheat (flour),0.22,2010
14,2010-01-01,Honduras,Wholesale,National Average,Beans (red),0.72,2010
15,2010-01-01,Costa Rica,Wholesale,National Average,Beans (red),1.87,2010
16,2010-01-01,Kazakhstan,Wholesale,National Average,Wheat (flour),0.35,2010
17,2010-01-01,Philippines,Wholesale,National Average,Maize (yellow),0.29,2010
18,2010-01-01,Chile,Wholesale,National Average,Maize (yellow),0.22,2010
19,2010-01-01,Philippines,Wholesale,National Average,Maize (white),0.37,2010
20,2010-01-01,Honduras,Wholesale,National Average,Maize (white),0.31,2010
21,2010-01-01,Guatemala,Wholesale,National Average,Maize (white),0.33,2010
22,2010-01-01,Costa Rica,Wholesale,National Average,Maize (white),0.50,2010
23,2010-01-01,Russian Federation,Wholesale,National Average,Maize,0.17,2010
24,2010-01-01,Israel,Wholesale,National Average,Maize,0.26,2010

In [23]:
filtered_first_day=filtered_first_day.sort_values('country', ascending=False)

filtered_first_day

,month,country,price_type,market,commodity,price,Year
128823,2010-01-01,Uzbekistan,Wholesale,National Average,Wheat (flour),0.29,2010
117850,2010-01-01,Ukraine,Wholesale,National Average,Wheat,0.15,2010
128949,2010-01-01,Ukraine,Wholesale,National Average,Wheat (flour),0.22,2010
33039,2010-01-01,Russian Federation,Wholesale,National Average,Maize,0.17,2010
118040,2010-01-01,Russian Federation,Wholesale,National Average,Wheat,0.15,2010
37016,2010-01-01,Philippines,Wholesale,National Average,Maize (white),0.37,2010
97419,2010-01-01,Philippines,Wholesale,National Average,Rice,0.62,2010
43336,2010-01-01,Philippines,Wholesale,National Average,Maize (yellow),0.29,2010
8997,2010-01-01,Kazakhstan,Wholesale,National Average,Beef meat,4.90,2010
122813,2010-01-01,Kazakhstan,Wholesale,National Average,Wheat (flour),0.35,2010
69939,2010-01-01,Kazakhstan,Wholesale,National Average,Potatoes,0.44,2010
129071,2010-01-01,Italy,Wholesale,National Average,Wheat (milling soft),0.21,2010
118410,2010-01-01,Italy,Wholesale,National Average,Wheat,0.24,2010
97169,2010-01-01,Italy,Wholesale,National Average,Rice,0.54,2010
29336,2010-01-01,Israel,Wholesale,National Average,Maize,0.26,2010
116312,2010-01-01,Israel,Wholesale,National Average,Wheat,0.25,2010
6594,2010-01-01,Honduras,Wholesale,National Average,Beans (red),0.72,2010
34513,2010-01-01,Honduras,Wholesale,National Average,Maize (white),0.31,2010
34015,2010-01-01,Guatemala,Wholesale,National Average,Maize (white),0.33,2010
2908,2010-01-01,Guatemala,Wholesale,National Average,Beans (black),1.01,2010
5353,2010-01-01,Costa Rica,Wholesale,National Average,Beans (red),1.87,2010
33520,2010-01-01,Costa Rica,Wholesale,National Average,Maize (white),0.50,2010
2287,2010-01-01,Costa Rica,Wholesale,National Average,Beans (black),1.64,2010
115109,2010-01-01,Chile,Wholesale,National Average,Wheat,0.23,2010
42624,2010-01-01,Chile,Wholesale,National Average,Maize (yellow),0.22,2010

In [24]:
difference_price['Price_Difference'] = filtered_last_day_index['price'] - test_two['price']
#we tried this and it didn't work because the indexes didn't match. This took alot of trial and error to fix

C:\Users\david\AppData\Local\Temp\ipykernel_17404\742383713.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  difference_price['Price_Difference'] = filtered_last_day_index['price'] - test_two['price']

In [25]:
#see comment above
filtered_last_day['price'] - test_two['price']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15       NaN
16       NaN
17       NaN
18       NaN
19       NaN
20       NaN
21       NaN
22       NaN
23       NaN
24       NaN
2167     NaN
2792     NaN
5233     NaN
6474     NaN
8878     NaN
29216    NaN
32919    NaN
33897    NaN
34394    NaN
36896    NaN
42505    NaN
43216    NaN
69820    NaN
97070    NaN
97299    NaN
114989   NaN
116192   NaN
117730   NaN
117920   NaN
118293   NaN
122694   NaN
128705   NaN
128829   NaN
128954   NaN
Name: price, dtype: float64

In [26]:
difference_price
#this will be used to create the bar chart.

,country,market,commodity,Price_Difference
0,Uzbekistan,National Average,Wheat (flour),-1.40
1,Ukraine,National Average,Wheat (flour),0.09
2,Ukraine,National Average,Wheat,0.01
3,Russian Federation,National Average,Maize,-0.28
4,Russian Federation,National Average,Wheat,-0.81
5,Philippines,National Average,Maize (white),0.09
6,Philippines,National Average,Rice,0.40
7,Philippines,National Average,Maize (yellow),0.28
8,Kazakhstan,National Average,Wheat (flour),-0.22
9,Kazakhstan,National Average,Potatoes,-0.28
10,Kazakhstan,National Average,Beef meat,5.41
11,Italy,National Average,Rice,0.10
12,Italy,National Average,Wheat,-4.60
13,Italy,National Average,Wheat (milling soft),0.00
14,Israel,National Average,Wheat,-0.42
15,Israel,National Average,Maize,-1.61
16,Honduras,National Average,Maize (white),0.04
17,Honduras,National Average,Beans (red),0.59
18,Guatemala,National Average,Beans (black),0.77
19,Guatemala,National Average,Maize (white),0.00
20,Costa Rica,National Average,Beans (black),1.45
21,Costa Rica,National Average,Beans (red),1.76
22,Chile,National Average,Wheat,-0.27
23,Chile,National Average,Maize (yellow),0.02

In [27]:
#https://files.slack.com/files-pri/T04HTQ9L1PZ-F05C628NPQB/image.png

In [28]:
last_day_data['price'] - first_day_data['price']
#see above

2167     NaN
2287     NaN
2792     NaN
2908     NaN
5233     NaN
5353     NaN
6474     NaN
6594     NaN
8878     NaN
8997     NaN
29216    NaN
29336    NaN
32919    NaN
33039    NaN
33520    NaN
33897    NaN
34015    NaN
34394    NaN
34513    NaN
36896    NaN
37016    NaN
42505    NaN
42624    NaN
43216    NaN
43336    NaN
69820    NaN
69939    NaN
80303    NaN
81860    NaN
97070    NaN
97169    NaN
97299    NaN
97419    NaN
114989   NaN
115109   NaN
115115   NaN
116192   NaN
116312   NaN
117478   NaN
117730   NaN
117850   NaN
117920   NaN
118040   NaN
118293   NaN
118410   NaN
122694   NaN
122813   NaN
128377   NaN
128705   NaN
128823   NaN
128829   NaN
128949   NaN
128954   NaN
129071   NaN
Name: price, dtype: float64

In [29]:
line_graph_annual_data_index_test =line_graph_annual_data.reset_index()

line_graph_annual_data_index_test.head(50)
#testing the dataframe here for the line test

    Year             country             commodity     price
0   2010               Chile        Maize (yellow)  0.222500
1   2010               Chile                 Wheat  0.217500
2   2010          Costa Rica         Beans (black)  1.693333
3   2010          Costa Rica           Beans (red)  1.897500
4   2010          Costa Rica         Maize (white)  0.534167
5   2010           Guatemala         Beans (black)  1.001667
6   2010           Guatemala         Maize (white)  0.327500
7   2010            Honduras           Beans (red)  1.119167
8   2010            Honduras         Maize (white)  0.286667
9   2010              Israel                 Maize  0.274167
10  2010              Israel                 Wheat  0.282500
11  2010               Italy                  Rice  0.586667
12  2010               Italy                 Wheat  0.242500
13  2010               Italy  Wheat (milling soft)  0.240000
14  2010          Kazakhstan             Beef meat  5.119091
15  2010          Kazakhstan              Potatoes  0.460000
16  2010          Kazakhstan         Wheat (flour)  0.366364
17  2010         Philippines         Maize (white)  0.333333
18  2010         Philippines        Maize (yellow)  0.319167
19  2010         Philippines                  Rice  0.630000
20  2010  Russian Federation                 Maize  0.210000
21  2010  Russian Federation                 Wheat  0.174167
22  2010             Ukraine                 Wheat  0.166667
23  2010             Ukraine         Wheat (flour)  0.258333
24  2010             Uruguay                  Rice  0.243000
25  2010             Uruguay                 Wheat  0.224000
26  2010          Uzbekistan         Wheat (flour)  0.287500
27  2011               Chile        Maize (yellow)  0.293333
28  2011               Chile                 Wheat  0.304167
29  2011          Costa Rica         Beans (black)  1.660833
30  2011          Costa Rica           Beans (red)  2.421667
31  2011          Costa Rica         Maize (white)  0.723333
32  2011           Guatemala         Beans (black)  1.034167
33  2011           Guatemala         Maize (white)  0.475000
34  2011            Honduras           Beans (red)  1.530000
35  2011            Honduras         Maize (white)  0.445833
36  2011              Israel                 Maize  0.370833
37  2011              Israel                 Wheat  0.385833
38  2011               Italy                  Rice  0.782222
39  2011               Italy                 Wheat  0.400833
40  2011               Italy  Wheat (milling soft)  0.341667
41  2011          Kazakhstan             Beef meat  6.895000
42  2011          Kazakhstan              Potatoes  0.679167
43  2011          Kazakhstan         Wheat (flour)  0.493333
44  2011         Philippines         Maize (white)  0.380833
45  2011         Philippines        Maize (yellow)  0.350000
46  2011         Philippines                  Rice  0.672500
47  2011  Russian Federation                 Maize  0.262500
48  2011  Russian Federation                 Wheat  0.215833
49  2011             Ukraine                 Wheat  0.219167

In [30]:
df_2010=line_graph_annual_data_index_test[line_graph_annual_data_index_test['Year']==2010]
line_graph_annual_data_index_test["commodity"].value_counts()
#we can look at the most common commodity to see what we might want to research and visualize. Below is wheat

Wheat                   73
Maize (white)           44
Rice                    40
Wheat (flour)           40
Maize (yellow)          22
Beans (black)           22
Beans (red)             22
Maize                   22
Wheat (milling soft)    11
Beef meat               11
Potatoes                11
Name: commodity, dtype: int64

In [31]:

#we need to reset the index

In [32]:
line_graph_annual_data_index_test

     Year     country       commodity     price
0    2010       Chile  Maize (yellow)  0.222500
1    2010       Chile           Wheat  0.217500
2    2010  Costa Rica   Beans (black)  1.693333
3    2010  Costa Rica     Beans (red)  1.897500
4    2010  Costa Rica   Maize (white)  0.534167
..    ...         ...             ...       ...
313  2020     Ukraine           Wheat  0.218333
314  2020     Ukraine   Wheat (flour)  0.315000
315  2020     Uruguay            Rice  0.186667
316  2020     Uruguay           Wheat  0.200000
317  2020  Uzbekistan   Wheat (flour)  0.281667

[318 rows x 4 columns]

In [33]:
#this is the graph we are going to create with this dataframe:#
#https://files.slack.com/files-pri/T04HTQ9L1PZ-F05C33P1GLD/image.png

In [34]:
#tested the dataframe and filtered for wheat so we can visualize wheat data 
line_graph_annual_data_index_test_wheat=line_graph_annual_data_index_test[line_graph_annual_data_index_test['commodity']=="Wheat"]
line_graph_annual_data_index_test_wheat.head(50)

     Year             country commodity     price
1    2010               Chile     Wheat  0.217500
10   2010              Israel     Wheat  0.282500
12   2010               Italy     Wheat  0.242500
21   2010  Russian Federation     Wheat  0.174167
22   2010             Ukraine     Wheat  0.166667
25   2010             Uruguay     Wheat  0.224000
28   2011               Chile     Wheat  0.304167
37   2011              Israel     Wheat  0.385833
39   2011               Italy     Wheat  0.400833
48   2011  Russian Federation     Wheat  0.215833
49   2011             Ukraine     Wheat  0.219167
52   2011             Uruguay     Wheat  0.301667
55   2012               Chile     Wheat  0.313333
64   2012              Israel     Wheat  0.354167
66   2012               Italy     Wheat  0.360833
75   2012  Russian Federation     Wheat  0.250833
76   2012             Ukraine     Wheat  0.224167
79   2012             Uruguay     Wheat  0.265000
82   2013               Chile     Wheat  0.328333
91   2013              Israel     Wheat  0.362500
93   2013               Italy     Wheat  0.369167
102  2013  Russian Federation     Wheat  0.278333
103  2013             Ukraine     Wheat  0.234167
106  2013             Uruguay     Wheat  0.318333
109  2014               Chile     Wheat  0.287500
111  2014               China     Wheat  0.409167
121  2014              Israel     Wheat  0.306667
123  2014               Italy     Wheat  0.407500
132  2014  Russian Federation     Wheat  0.225833
133  2014             Ukraine     Wheat  0.193333
136  2014             Uruguay     Wheat  0.261667
139  2015               Chile     Wheat  0.247500
141  2015               China     Wheat  0.392500
151  2015              Israel     Wheat  0.252500
153  2015               Italy     Wheat  0.346667
162  2015  Russian Federation     Wheat  0.171667
163  2015             Ukraine     Wheat  0.158333
166  2015             Uruguay     Wheat  0.212500
169  2016               Chile     Wheat  0.203333
171  2016               China     Wheat  0.354167
181  2016              Israel     Wheat  0.235000
183  2016               Italy     Wheat  0.242500
192  2016  Russian Federation     Wheat  0.164167
193  2016             Ukraine     Wheat  0.155833
196  2016             Uruguay     Wheat  0.165833
199  2017               Chile     Wheat  0.204167
201  2017               China     Wheat  0.366667
211  2017              Israel     Wheat  0.252500
213  2017               Italy     Wheat  0.245000
222  2017  Russian Federation     Wheat  0.166667

In [35]:
bar_wheat_2020=line_graph_annual_data_index_test_wheat[line_graph_annual_data_index_test_wheat['Year']==2020]

bar_wheat_2020
bar_wheat_2020.sort_values(by='price',ascending=False)
mtw_no_china = bar_wheat_2020.drop(291)
bar_wheat_2020_final=mtw_no_china.sort_values(by='country',ascending=False)

bar_wheat_2020_final

     Year             country commodity     price
316  2020             Uruguay     Wheat  0.200000
313  2020             Ukraine     Wheat  0.218333
312  2020  Russian Federation     Wheat  0.198333
303  2020               Italy     Wheat  0.310000
301  2020              Israel     Wheat  0.308000
289  2020               Chile     Wheat  0.233333

In [36]:
bar_wheat_2010= line_graph_annual_data_index_test_wheat[line_graph_annual_data_index_test_wheat['Year']==2010]
bar_wheat_2010_final=bar_wheat_2010.sort_values(by='country',ascending=False)
bar_wheat_2010_final

    Year             country commodity     price
25  2010             Uruguay     Wheat  0.224000
22  2010             Ukraine     Wheat  0.166667
21  2010  Russian Federation     Wheat  0.174167
12  2010               Italy     Wheat  0.242500
10  2010              Israel     Wheat  0.282500
1   2010               Chile     Wheat  0.217500

In [40]:
line_graph_annual_data_index_test["commodity"].unique()

array(['Maize (yellow)', 'Wheat', 'Beans (black)', 'Beans (red)',
       'Maize (white)', 'Maize', 'Rice', 'Wheat (milling soft)',
       'Beef meat', 'Potatoes', 'Wheat (flour)'], dtype=object)

In [41]:
bar_wheat_2020_final.to_csv("charting-dataframe/bar_wheat_2020.csv",index=False)
bar_wheat_2010_final.to_csv("charting-dataframe/bar_wheat_2010.csv",index=False)
difference_price.to_csv("charting-dataframe/10_year_price_difference_data.csv",index=False)
line_graph_annual_data_index_test_wheat.to_csv("charting-dataframe/annual_data_wheat.csv",index=False)
line_graph_annual_data_index_test.to_csv("charting-dataframe/line_graph_annual_data.csv",index=False)