In [1]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

In [2]:
CovidFoodPriceChange_df = pd.read_csv('Resources/dom_change_percent.csv')
CovidFoodPriceChange_df.head(25)

,Unnamed: 0,country,price_type,market,commodity,percent,post_covid,yearly
0,0,Cote d'Ivoire,Retail,Abidjan,AttiÃ©kÃ©,NaN,-0.061538,-0.031746
1,1,Cameroon,Retail,YaundÃ©,Bananas (plantains),NaN,0.000000,0.000000
2,2,Cameroon,Retail,Bafoussam,Bananas (plantains),NaN,-0.305556,0.041667
3,3,Morocco,Retail,National Average,Barley (imported),NaN,-0.034483,-0.034483
4,4,Cote d'Ivoire,Retail,Abidjan,Banana (plantains),NaN,0.769231,0.232143
5,5,Morocco,Retail,National Average,Barley (local),NaN,0.588235,1.076923
6,6,Cameroon,Retail,Douala,Bananas (plantains),NaN,-0.117647,-0.021739
7,7,Democratic Republic of the Congo,Retail,Bukavu,Beans,NaN,-0.112676,0.852941
8,8,Cameroon,Retail,Bamenda,Bananas (plantains),NaN,0.029412,0.060606
9,9,Democratic Republic of the Congo,Retail,Goma,Beans,NaN,0.333333,0.632653
10,10,Rwanda,Wholesale,Kigali,Beans,NaN,-0.122807,-0.166667
11,11,Democratic Republic of the Congo,Retail,Lubumbashi,Beans,NaN,0.371212,0.000000
12,12,Rwanda,Wholesale,Ruhengeri,Beans,NaN,-0.056604,0.000000
13,13,Costa Rica,Retail,National Average,Beans (black),NaN,0.014563,0.060914
14,14,United Republic of Tanzania,Wholesale,Dar es Salaam,Beans,NaN,0.000000,0.228571
15,15,Uganda,Wholesale,Lira,Beans,NaN,0.174603,0.121212
16,16,Uganda,Wholesale,Kampala,Beans,NaN,0.250000,0.214286
17,17,Costa Rica,Wholesale,National Average,Beans (black),NaN,0.050000,0.067797
18,18,Haiti,Retail,Cap Haitien,Beans (black),NaN,0.204545,0.522989
19,19,Dominican Republic,Retail,Santo Domingo,Beans (black),NaN,0.032787,0.131737
20,20,Dominican Republic,Wholesale,Santo Domingo,Beans (black),NaN,0.024390,0.244444
21,21,Guatemala,Wholesale,Guatemala City,Beans (black),NaN,0.355769,0.532609
22,22,Guatemala,Wholesale,National Average,Beans (black),NaN,0.352941,0.516484
23,23,Haiti,Retail,Ouanaminthe,Beans (black),NaN,0.055556,0.419540
24,24,Haiti,Retail,Les Cayes,Beans (black),NaN,0.060109,0.375887

In [3]:
CovidFoodPriceChange_df.shape

(1144, 8)

In [4]:
CovidFoodPriceChange_df.info

<bound method DataFrame.info of       Unnamed: 0        country price_type            market  \
0              0  Cote d'Ivoire     Retail           Abidjan
1              1       Cameroon     Retail           YaundÃ©
2              2       Cameroon     Retail         Bafoussam
3              3        Morocco     Retail  National Average
4              4  Cote d'Ivoire     Retail           Abidjan
...          ...            ...        ...               ...
1139        1139          Benin     Retail           Parakou
1140        1140          Benin     Retail        Natitingou
1141        1141          Benin     Retail           Cotonou
1142        1142          Ghana  Wholesale            Tamale
1143        1143          Ghana  Wholesale          Techiman

                commodity  percent  post_covid    yearly
0               AttiÃ©kÃ©      NaN   -0.061538 -0.031746
1     Bananas (plantains)      NaN    0.000000  0.000000
2     Bananas (plantains)      NaN   -0.305556  0.041667
3       Barley (imported)      NaN   -0.034483 -0.034483
4      Banana (plantains)      NaN    0.769231  0.232143
...                   ...      ...         ...       ...
1139                  Yam      NaN    0.057143  0.027778
1140                  Yam      NaN    0.088235  0.057143
1141                  Yam      NaN    0.057692  0.100000
1142                  Yam      NaN   -0.090909  0.000000
1143                  Yam      NaN    0.700000 -0.128205

[1144 rows x 8 columns]>

In [5]:
CovidFoodPriceChange_df['commodity'].value_counts()

Rice                195
Sorghum              98
Wheat (flour)        90
Potatoes             72
Millet               69
                   ...
Cassava               1
Pasta                 1
Beans (white)         1
Potatoes (white)      1
AttiÃ©kÃ©             1
Name: commodity, Length: 84, dtype: int64

In [6]:
CovidFoodPriceChange_df['market'].unique()

array(['Abidjan', 'YaundÃ©', 'Bafoussam', 'National Average', 'Douala',
       'Bukavu', 'Bamenda', 'Goma', 'Kigali', 'Lubumbashi', 'Ruhengeri',
       'Dar es Salaam', 'Lira', 'Kampala', 'Cap Haitien', 'Santo Domingo',
       'Guatemala City', 'Ouanaminthe', 'Les Cayes', 'Jeremie', 'Jacmel',
       'Hinche', 'Port-au-Prince', 'Guadalajara', 'Puebla', 'Mexico City',
       'Xalapa', 'Panama City', 'San Salvador', 'Garoua',
       'San Pedro Sula', 'Tegucigalpa', 'Managua (oriental)',
       'Greater Buenos Aires', 'Aktau', 'Almaty', 'Kostanay',
       'Nur-Sultan', 'Batken', 'Bishkek', 'Jalal-Abad', 'Naryn', 'Osh',
       'Nouakchott', 'Selenge', 'Dornod', 'Bayan-Ulgii', 'Jalalabad',
       'Herat', 'Kabul', 'Kandahar', 'Ulaanbaatar', 'Uvurkhangai',
       'Potosi', 'Santiago', 'Bulawayo', 'Manicaland', 'Harare',
       'Mash east', 'Mash central', 'Masvingo', 'Mash west', 'Lima',
       'SÃ£o Paulo', 'Mat north', 'Mat south', 'Midlands', 'Hhohho',
       'Manzini', 'Lubombo', 'Minsk', 'National average', 'Shiselweni',
       'Gaza Strip', 'West Bank', 'Tokyo', 'Osaka', 'Juba', 'Nampula',
       'Luanda', 'Bangkok', 'AsunciÃ³n', 'Cotonou', 'S.Vincente',
       'Natitingou', 'Parakou', 'Amegnran', 'Anie', 'CinkassÃ©', 'Kara',
       'Korbongou', 'LomÃ©', 'S.AntÃ£o', 'Accra', 'Tamale', 'Techiman',
       'Mzuzu', 'Cochabamba', 'La Paz', 'Oruro', 'Santa Cruz', 'Sucre',
       'Tarija', 'Trinidad', 'Hadramout', 'Dhamar', 'New Delhi', 'Mumbai',
       'Chennai', 'Hajjah', 'Hodeidah', 'Yangon', 'Ibadan', 'Kano',
       'Kaura Namoda', 'Lagos', 'Maiduguri', 'Bujumbura', 'Ngozi',
       'Gitega', "N'Djamena", 'Bol', 'Moussoro', 'Ambato', 'Mekele',
       'Diredawa', 'Bahirdar', 'Guayaquil', 'Quito', 'Riobamba',
       'Addis Ababa', 'Kumasi', 'Bolgatanga', 'Kisumu', 'Eldoret',
       'Liwonde', 'Lilongwe', 'Nakuru', 'Nairobi', 'Mombasa', 'Zinder',
       'Tillaberi', 'Niamey', 'Maradi', 'Dosso', 'Mzimba', 'Nsanje',
       'Agadez', 'Arusha', 'Masindi', 'Kabale', 'Conakry', 'MedellÃ\xadn',
       'Angonia', 'Chokwe', 'Gorongosa', 'Manica', 'Maputo', 'Montepuez',
       'Ribaue', 'Giwa', 'South Cotabato', 'Belet Weyne', 'Baidoa',
       'Hargeisa', 'Borama', 'Buale', 'Galkayo', 'Hudur', 'Kismayo',
       'Marka', 'Mogadishu', 'Qorioley', 'Randfontein', 'Aweil', 'Bor',
       'Gogrial', 'Rumbek', 'Torit', 'Wau', 'Yambio', 'CuliacÃ¡n',
       'Davao City', 'Cebu', 'Rosario', 'Mato Grosso', 'Federal District',
       'ParanÃ¡', 'Rio Grande do Sul', 'Portoviejo', 'Cuenca',
       'Cartagena', 'BogotÃ¡', 'MetroManila', 'Katima', 'Gobabis',
       'Keetmanshoop', 'Mariental', 'Oshakati', 'Otjiwarongo',
       'Swakopmund', 'Windhoek', 'Ahmedabad', 'Bengaluru', 'Bhopal',
       'Patna', 'Abeche', 'Moundou', 'Sarh', 'Kaolack', 'Fatick',
       'Diourbel', 'Dakar', 'El Gedarif', 'Al-Fashir', 'Kolda', 'Louga',
       'Matam', 'SaintLouis', 'Tambacounda', 'Thies', 'Zguinchor',
       'Al-Damazin', 'El Obeid', 'Kadugli', 'Khartoum', 'Nyala',
       'Port Sudan', 'Bobo Dioulasso', 'Dori', 'DÃ©dougou',
       "Fada N'gourma", 'Kongoussi', 'Nouna', 'Ouagadougou', 'Tenkodogo',
       'Bamako', 'Gao', 'Kayes', 'Mopti', 'Sikasso', 'SÃ©gou',
       'Tombouctou', 'Bo', 'Freetown', 'Kailahun', 'Kenema', 'Koinadugu',
       'Iloilo', 'Nueva Ecija', 'Khorugh', 'Khatlon', 'Dushanbe',
       'Khujand', 'Kurgonteppa', 'Sughd', 'Kampot', 'Maxixe', 'Dhaka',
       'Phnom Penh', 'Kampong Chhnang', 'Battambang', 'Banteay Meanchey',
       'Multan', 'Karachi', 'Lahore', 'Quetta', 'Kathmandu', 'Saclepea',
       'Monrovia', 'Buchanan', 'Bossaso', 'Lasanod', 'Colombo', 'Dongola',
       'Dinsoor', 'Kampong Cham', 'Barranquilla', 'Buenos Aires',
       'Peshawar', 'Bale Robe', 'Debre Marcos', 'Jimma', 'Shashemene'],
      dtype=object)

In [7]:
CovidFoodPriceChange_df['market']

0                Abidjan
1                YaundÃ©
2              Bafoussam
3       National Average
4                Abidjan
              ...
1139             Parakou
1140          Natitingou
1141             Cotonou
1142              Tamale
1143            Techiman
Name: market, Length: 1144, dtype: object

In [8]:
market_column = CovidFoodPriceChange_df.loc[:,'market']
national_average_data = CovidFoodPriceChange_df[CovidFoodPriceChange_df['market'] == 'National Average']

In [9]:
national_average_data

,Unnamed: 0,country,price_type,market,commodity,percent,post_covid,yearly
3,3,Morocco,Retail,National Average,Barley (imported),NaN,-0.034483,-0.034483
5,5,Morocco,Retail,National Average,Barley (local),NaN,0.588235,1.076923
13,13,Costa Rica,Retail,National Average,Beans (black),NaN,0.014563,0.060914
17,17,Costa Rica,Wholesale,National Average,Beans (black),NaN,0.050000,0.067797
22,22,Guatemala,Wholesale,National Average,Beans (black),NaN,0.352941,0.516484
...,...,...,...,...,...,...,...,...
1124,1124,Tajikistan,Retail,National Average,Wheat (flour),NaN,0.243243,0.210526
1125,1125,Uzbekistan,Wholesale,National Average,Wheat (flour),NaN,0.520000,0.727273
1126,1126,Ukraine,Wholesale,National Average,Wheat (flour),NaN,0.000000,0.000000
1127,1127,Italy,Wholesale,National Average,Wheat (milling soft),NaN,0.047619,-0.083333
1134,1134,Zambia,Retail,National Average,White roller maize meal,NaN,-0.324324,-0.074074

In [10]:
CovidFoodPriceChange_df_copy=CovidFoodPriceChange_df.copy()
CovidFoodPriceChange_df_copy

,Unnamed: 0,country,price_type,market,commodity,percent,post_covid,yearly
0,0,Cote d'Ivoire,Retail,Abidjan,AttiÃ©kÃ©,NaN,-0.061538,-0.031746
1,1,Cameroon,Retail,YaundÃ©,Bananas (plantains),NaN,0.000000,0.000000
2,2,Cameroon,Retail,Bafoussam,Bananas (plantains),NaN,-0.305556,0.041667
3,3,Morocco,Retail,National Average,Barley (imported),NaN,-0.034483,-0.034483
4,4,Cote d'Ivoire,Retail,Abidjan,Banana (plantains),NaN,0.769231,0.232143
...,...,...,...,...,...,...,...,...
1139,1139,Benin,Retail,Parakou,Yam,NaN,0.057143,0.027778
1140,1140,Benin,Retail,Natitingou,Yam,NaN,0.088235,0.057143
1141,1141,Benin,Retail,Cotonou,Yam,NaN,0.057692,0.100000
1142,1142,Ghana,Wholesale,Tamale,Yam,NaN,-0.090909,0.000000
1143,1143,Ghana,Wholesale,Techiman,Yam,NaN,0.700000,-0.128205

In [11]:
incorrect_city_list=["MedellÃn", "CuliacÃ¡n", "Federal District","ParanÃ¡","BogotÃ¡", "MetroManila", "CuliacÃ¡n",
"DÃ©dougou", "SÃ©gou","Tombouctou",'YaundÃ©', 'SÃ£o Paulo', 'AsunciÃ³n', 'S.Vincente', 'CinkassÃ©', 'LomÃ©', 'S.AntÃ£o']
corrected_city_list = ["Medellín","Culiacán","Distrito Federal","Paraná","Bogotá","Metro Manila","Culiacán","Dédougou","Ségou"
                       ,"Timbuktu",'Yaoundé', 'São Paulo', 'Asunción', 'São Vicente', 'Cinkassé', 'Lomé', 'Santo Antão']
#if we made this into a dictionary, where the incorrect cities would be the key and the correct cities would be the value, if 
#the market value is in the list of keys, then set the market value equal to correct value

cities_dict = dict(zip(incorrect_city_list, corrected_city_list))
cities_dict

#for index, row in CovidFoodPriceChange_df_copy.iterrows():
#    if row['market'] in cities_dict.keys():
#        market_key = row['market']
#        row['market']= cities_dict[market_key]

{'MedellÃn': 'Medellín',
 'CuliacÃ¡n': 'Culiacán',
 'Federal District': 'Distrito Federal',
 'ParanÃ¡': 'Paraná',
 'BogotÃ¡': 'Bogotá',
 'MetroManila': 'Metro Manila',
 'DÃ©dougou': 'Dédougou',
 'SÃ©gou': 'Ségou',
 'Tombouctou': 'Timbuktu',
 'YaundÃ©': 'Yaoundé',
 'SÃ£o Paulo': 'São Paulo',
 'AsunciÃ³n': 'Asunción',
 'S.Vincente': 'São Vicente',
 'CinkassÃ©': 'Cinkassé',
 'LomÃ©': 'Lomé',
 'S.AntÃ£o': 'Santo Antão'}

In [12]:
CovidFoodPriceChange_df_copy['market'] = CovidFoodPriceChange_df_copy['market'].replace(cities_dict)

In [13]:
CovidFoodPriceChange_df_copy.head(20)

,Unnamed: 0,country,price_type,market,commodity,percent,post_covid,yearly
0,0,Cote d'Ivoire,Retail,Abidjan,AttiÃ©kÃ©,NaN,-0.061538,-0.031746
1,1,Cameroon,Retail,Yaoundé,Bananas (plantains),NaN,0.000000,0.000000
2,2,Cameroon,Retail,Bafoussam,Bananas (plantains),NaN,-0.305556,0.041667
3,3,Morocco,Retail,National Average,Barley (imported),NaN,-0.034483,-0.034483
4,4,Cote d'Ivoire,Retail,Abidjan,Banana (plantains),NaN,0.769231,0.232143
5,5,Morocco,Retail,National Average,Barley (local),NaN,0.588235,1.076923
6,6,Cameroon,Retail,Douala,Bananas (plantains),NaN,-0.117647,-0.021739
7,7,Democratic Republic of the Congo,Retail,Bukavu,Beans,NaN,-0.112676,0.852941
8,8,Cameroon,Retail,Bamenda,Bananas (plantains),NaN,0.029412,0.060606
9,9,Democratic Republic of the Congo,Retail,Goma,Beans,NaN,0.333333,0.632653
10,10,Rwanda,Wholesale,Kigali,Beans,NaN,-0.122807,-0.166667
11,11,Democratic Republic of the Congo,Retail,Lubumbashi,Beans,NaN,0.371212,0.000000
12,12,Rwanda,Wholesale,Ruhengeri,Beans,NaN,-0.056604,0.000000
13,13,Costa Rica,Retail,National Average,Beans (black),NaN,0.014563,0.060914
14,14,United Republic of Tanzania,Wholesale,Dar es Salaam,Beans,NaN,0.000000,0.228571
15,15,Uganda,Wholesale,Lira,Beans,NaN,0.174603,0.121212
16,16,Uganda,Wholesale,Kampala,Beans,NaN,0.250000,0.214286
17,17,Costa Rica,Wholesale,National Average,Beans (black),NaN,0.050000,0.067797
18,18,Haiti,Retail,Cap Haitien,Beans (black),NaN,0.204545,0.522989
19,19,Dominican Republic,Retail,Santo Domingo,Beans (black),NaN,0.032787,0.131737

In [14]:

                                           
CampaignClean = CovidFoodPriceChange_df_copy.drop(columns=["Unnamed: 0","percent"])
#CampaignClean=CampaignClean.drop(0)
CampaignClean.head()

,country,price_type,market,commodity,post_covid,yearly
0,Cote d'Ivoire,Retail,Abidjan,AttiÃ©kÃ©,-0.061538,-0.031746
1,Cameroon,Retail,Yaoundé,Bananas (plantains),0.000000,0.000000
2,Cameroon,Retail,Bafoussam,Bananas (plantains),-0.305556,0.041667
3,Morocco,Retail,National Average,Barley (imported),-0.034483,-0.034483
4,Cote d'Ivoire,Retail,Abidjan,Banana (plantains),0.769231,0.232143

In [26]:
CampaignClean['commodity'].unique()
value_fix={'AttiÃ©kÃ©':'Attieke'}

array(['AttiÃ©kÃ©', 'Bananas (plantains)', 'Barley (imported)',
       'Banana (plantains)', 'Barley (local)', 'Beans', 'Beans (black)',
       'Beans (poroto)', 'Beans (red)', 'Beans (wild)', 'Beans (white)',
       'Beef meat', 'Bread', 'Bread (Sabbath loaf)',
       'Bread (French type)', 'Bread (brown)', 'Bread (high grade flour)',
       'Bread (first grade flour)', 'Bread (white)', 'Cabbage',
       'Breakfast maize meal', 'Camel meat', 'Cassava', 'Cassava (dry)',
       'Cassava (flour)', 'Cassava (fresh)', 'Cassava (gari)',
       'Cassava (manioc)', 'Cassava (root)', 'Chicken (without offals)',
       'Chicken (processed)', 'Chicken meat', 'Chickpeas', 'Lentils',
       'Lamb meat', 'Groundnuts', 'Groundnut Oil', 'Gari (white)', 'Gram',
       'Maize', 'Maize (flour)', 'Maize (local)', 'Maize (white)',
       'Maize (white flour)', 'Maize (yellow)', 'Maize (yellow flour)',
       'Maize meal', 'Maize meal (local)', 'Milk', 'Milk (Camel)',
       'Milk (powder)', 'Millet', 'Mutton meat', 'Olive Oil', 'Palm Oil',
       'Onions', 'Pasta', 'Plantains', 'Pork meat',
       'Pork meat with bones', 'Potatoes', 'Quinoa', 'Potatoes (white)',
       'Prawn', 'Rice', 'Radish', 'Rice (imported)', 'Rice ', 'Samp',
       'Sorghum', 'Semolina', 'Soya beans', 'Sugar', 'Tortillas',
       'Tomatoes', 'Taro', 'Teff (mixed)', 'Wheat', 'Vegetable oil',
       'Wheat (flour)', 'Wheat (milling soft)', 'Wheat (white)',
       'White roller maize meal', 'Yam'], dtype=object)

In [27]:
CampaignClean['commodity'] = CampaignClean['commodity'].replace(value_fix)

In [35]:
value_fix={'Yaoundé':'Yaounde'}
CampaignClean['market'] = CampaignClean['market'].replace(value_fix)
#we found that this charcther wouldn't translate into excel or mongodb so we chose to omit it and replace it with a 
#similar charcther

In [36]:
CampaignClean.head()

,country,price_type,market,commodity,post_covid,yearly
0,Cote d'Ivoire,Retail,Abidjan,Attieke,-0.061538,-0.031746
1,Cameroon,Retail,Yaounde,Bananas (plantains),0.000000,0.000000
2,Cameroon,Retail,Bafoussam,Bananas (plantains),-0.305556,0.041667
3,Morocco,Retail,National Average,Barley (imported),-0.034483,-0.034483
4,Cote d'Ivoire,Retail,Abidjan,Banana (plantains),0.769231,0.232143

In [38]:
CampaignClean.to_csv("percent_change_post_covid.csv",index=False)